# Generated by Django 4.1.7 on 2023-03-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sName', models.CharField(max_length=100)),
                ('sRollno', models.IntegerField()),
                ('sEmail', models.EmailField(max_length=254)),
                ('sPassword', models.CharField(max_length=100)),
                ('sAge', models.PositiveIntegerField()),
                ('sCollege', models.CharField(max_length=100)),
                ('sStatus', models.BooleanField(default=True)),
                ('sTermDate', models.DateField()),
                ('sResult', models.FloatField(verbose_name='percentage ')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
