# Generated by Django 4.1.7 on 2023-03-02 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='students1',
        ),
    ]
