# Generated by Django 4.1.7 on 2023-03-02 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
