# Generated by Django 4.1.7 on 2023-03-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0003_food_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
